package com.example.myapplication

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }
}

//From the demonstration, we replaced the "code" with "token"
//https://some-prefix-domain-name.auth.us-east-1.amazoncognito.com/login?response_type=code&client_id=<your_app_client_id>&redirect_uri=<your_callback_url>
//somePassword123#
//https://my-web-proj.herokuapp.com/#id_token=eyJraWQiOiJKOUFjdmhGYzNlNER2YmZaeUxKcUhwbDZ4S1d1aXFXOXIycnhSdndvTkFzPSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoicWZBMmFSY3hjQUx4RGphQng0RUlvZyIsInN1YiI6Ijg1YWRlZTBiLWNhNDUtNDZiNC04NGM5LTY2ZGY5ZjA4NTg0ZSIsImF1ZCI6IjdoMXNudGRtNWoxcnRwOWs3ZDZkdWdsdmhqIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImV2ZW50X2lkIjoiMjg2N2JjYjItMzZmMC00YzBkLTk5N2UtOTQzNjY3MmExODhkIiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE1NzAxNTkxMDQsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xXzJYOWhNVG1ZayIsImNvZ25pdG86dXNlcm5hbWUiOiI4NWFkZWUwYi1jYTQ1LTQ2YjQtODRjOS02NmRmOWYwODU4NGUiLCJleHAiOjE1NzAxNjI3MDQsImlhdCI6MTU3MDE1OTEwNCwiZW1haWwiOiJkbGVlbXN1OTZAZ21haWwuY29tIn0.yx9Hhw8NLx3IPbCS1AwWjmsqXUbNzVOL7UjziLhHDUXWNNcyHuv0irz4ck0PlEWyNSwJbK6LDPJThk7F3UQlySDEFOnhM_H45FcwC6Q5lvVEJiBJ9qMwNlOzb5i9LUF2v6wZwtPG8DHrc9KDkh0hXSiRULZUaf8nkq2rRL-OgINWSSlEw8F12DtyIndUoHmhag0WZh1zW1hhjb_qOfDpxXs_498ResjCQ6-PmhmmWxtFLez33eFrd-jgmDdcA7rnobcYdYcmw7k8Dpu0mITbsDu-q5gVs6mQzauHOERKvpjjF-rQwzMTLpd4cOYlf97y0dUBS0qt8GIB5Vyx6x_XNA&access_token=eyJraWQiOiJYeVAxZ2tcL0VLZ01aVmt2V1ZqQmt4cE52bWQwSW9MT0NJYmNRUXZVVDhkTT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI4NWFkZWUwYi1jYTQ1LTQ2YjQtODRjOS02NmRmOWYwODU4NGUiLCJldmVudF9pZCI6IjI4NjdiY2IyLTM2ZjAtNGMwZC05OTdlLTk0MzY2NzJhMTg4ZCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4gcGhvbmUgb3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhdXRoX3RpbWUiOjE1NzAxNTkxMDQsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xXzJYOWhNVG1ZayIsImV4cCI6MTU3MDE2MjcwNCwiaWF0IjoxNTcwMTU5MTA0LCJ2ZXJzaW9uIjoyLCJqdGkiOiJiYzE0ODI3ZC00ZjMzLTQ3ZTMtODcyOS02NTQxYTliYmZjNWIiLCJjbGllbnRfaWQiOiI3aDFzbnRkbTVqMXJ0cDlrN2Q2ZHVnbHZoaiIsInVzZXJuYW1lIjoiODVhZGVlMGItY2E0NS00NmI0LTg0YzktNjZkZjlmMDg1ODRlIn0.Nq91ulDnEz39Ewu60-VM_aUQEqzHa9SHE0aIQgHplrECgtR2dxmcvvoYOYWor77fzhrFWMXpwPMrTBIO294Lgaz7P2BfXMmr1lfplQx7-_4ZgtRj4mFb6v3rJFjODA2DIATtDfRVD79mnk6waO3ogAIHKnSNzj5aqP6yvex7PemjsKX5Y_HeEerZ3vRc84tATduDua_mHQsZbaVzx9CNCjU_V8bB0DRFXYwLJrp2yl5GcOVxXsw3XeIxUiueQEjplDCLgLtB0oBx42jY0oBeJZKPa0rajxsN1oOBNYLwu1AWGKNeAFE8GkU2phxI_aLX-t6OhRfCAexkktmaP_aucQ&expires_in=3600&token_type=Bearer
//With the value assigned to id token above, you can decrypt the thing via the link below:
//https://jwt.io
//Which was pretty sick.